/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 log.glb -T -S -I -t
*/

import * as THREE from 'three';
import { useMemo, useContext, createContext } from 'react';
import { useGLTF, Merged } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { CuboidCollider, RigidBody } from '@react-three/rapier';
import { useAsset } from '@/store/CanvasProvider';

type GLTFResult = GLTF & {
  nodes: {
    log_Baked_Baked: THREE.Mesh;
  };
  materials: {
    log_Baked_Baked: THREE.MeshStandardMaterial;
  };
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>
>;

const context = createContext({} as ContextType);
export function Instances({
  children,
  ...props
}: JSX.IntrinsicElements['group']) {
  const model = useAsset('log');
  const { nodes } = model as GLTFResult;
  const instances = useMemo(
    () => ({
      LogBakedBaked: nodes.log_Baked_Baked,
    }),
    [nodes],
  );
  return (
    <Merged meshes={instances} {...props}>
      {(instances: ContextType) => (
        <context.Provider value={instances}>{children}</context.Provider>
      )}
    </Merged>
  );
}

export default function Log(props: JSX.IntrinsicElements['group']) {
  const instances = useContext(context);
  return (
    <group scale={1.5} {...props} dispose={null}>
      <RigidBody type="fixed" colliders={false}>
        <CuboidCollider args={[0.5, 0.2, 0.2]} />
        <instances.LogBakedBaked />
      </RigidBody>
    </group>
  );
}

useGLTF.preload('/assets/models/log.glb');
