/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 mountain.glb -T -S -t
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { useAsset } from '@/store';

type GLTFResult = GLTF & {
  nodes: {
    Plane: THREE.Mesh;
  };
  materials: {
    ['Material.007']: THREE.MeshStandardMaterial;
  };
};

export default function Mountain(props: JSX.IntrinsicElements['group']) {
  const model = useAsset('mountain');
  const { nodes, materials } = model as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials['Material.007']}
        position={[0, -0.18, -8.5]}
        rotation={[0.93, 0, 0]}
        scale={[18.23, 17, 8.55]}
      />
    </group>
  );
}

useGLTF.preload('/assets/models/mountain.glb');
