/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 oak.glb -T -S -I -t
*/

import * as THREE from 'three';
import { useMemo, useContext, createContext } from 'react';
import { useGLTF, Merged } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { CuboidCollider, RigidBody } from '@react-three/rapier';
import { useAsset } from '@/store/CanvasProvider';

type GLTFResult = GLTF & {
  nodes: {
    oak_leef: THREE.Mesh;
    oak: THREE.Mesh;
  };
  materials: {
    oak_leef: THREE.MeshStandardMaterial;
    oak: THREE.MeshStandardMaterial;
  };
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>
>;

const context = createContext({} as ContextType);
export function Instances({
  children,
  ...props
}: JSX.IntrinsicElements['group']) {
  const model = useAsset('oak');
  const { nodes } = model as GLTFResult;

  const instances = useMemo(
    () => ({
      Oakleef: nodes.oak_leef,
      Oak: nodes.oak,
    }),
    [nodes],
  );
  return (
    <Merged meshes={instances} {...props}>
      {(instances: ContextType) => (
        <context.Provider value={instances}>{children}</context.Provider>
      )}
    </Merged>
  );
}

export default function Oak(props: JSX.IntrinsicElements['group']) {
  const instances = useContext(context);
  return (
    <group {...props} dispose={null}>
      <RigidBody type={'fixed'} colliders={false}>
        <CuboidCollider args={[0.3, 0.25, 0.3]} position={[0, 0.4, 0]} />
        <instances.Oakleef castShadow />
        <instances.Oak />
      </RigidBody>
    </group>
  );
}

useGLTF.preload('/assets/models/oak.glb');
