/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 whiteflower.glb -T -S -I -t
*/

import * as THREE from 'three';
import React, { useRef, useMemo, useContext, createContext } from 'react';
import { useGLTF, Merged } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { useAsset } from '@/store/CanvasProvider';
import { whiteflowerModelPath } from '@/contants';

type GLTFResult = GLTF & {
  nodes: {
    whiteFlower: THREE.Mesh;
  };
  materials: {
    whiteFlower: THREE.MeshStandardMaterial;
  };
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>
>;

const context = createContext({} as ContextType);
export function Instances({
  children,
  ...props
}: JSX.IntrinsicElements['group']) {
  const model = useAsset('whiteflower');
  const { nodes } = model as GLTFResult;
  const instances = useMemo(
    () => ({
      WhiteFlower: nodes.whiteFlower,
    }),
    [nodes],
  );
  return (
    <Merged meshes={instances} {...props}>
      {(instances: ContextType) => (
        <context.Provider value={instances}>{children}</context.Provider>
      )}
    </Merged>
  );
}

export default function Whiteflower(props: JSX.IntrinsicElements['group']) {
  const instances = useContext(context);
  const group = useRef<THREE.Group>(null);
  return (
    <group scale={1.4} ref={group} {...props} dispose={null}>
      <group name="Scene">
        <instances.WhiteFlower name="whiteFlower" />
      </group>
    </group>
  );
}

useGLTF.preload(whiteflowerModelPath);
